import { observer } from "mobx-react-lite";
import { useStore } from "../../stores/storeContext";
import { PageHeader } from "../_shared/PageHeader";
import { THEMES, THEME_IDS } from "../../core/themes";

const NUMBER_WORDS: Record<number, string> = {
  1: "one",
  2: "two",
  3: "three",
  4: "four",
  5: "five",
  6: "six",
  7: "seven",
  8: "eight",
  9: "nine",
  10: "ten",
  11: "eleven",
  12: "twelve",
  13: "thirteen",
  14: "fourteen",
  15: "fifteen",
  16: "sixteen",
  17: "seventeen",
  18: "eighteen",
  19: "nineteen",
  20: "twenty",
};

function spellOut(n: number): string {
  return NUMBER_WORDS[n] ?? n.toLocaleString();
}

export const AboutView = observer(function AboutView() {
  const { data, theme } = useStore();
  const index = data.index.status === "ready" ? data.index.value : null;
  const activeTheme = THEMES[theme.theme];
  const editionCount = THEME_IDS.length;

  return (
    <article className="max-w-prose">
      <PageHeader
        folio="VII"
        eyebrow="Colophon"
        title={
          <>
            About this{" "}
            <span className="italic text-oxblood-500" style={{ fontVariationSettings: '"opsz" 144, "SOFT" 80, "WONK" 1' }}>
              volume
            </span>
            .
          </>
        }
      />

      <div className="dropcap font-serif text-[17px] leading-relaxed text-ink-300 space-y-5">
        <p>
          The N2K Almanac is a complete reference for the dice-and-equation game
          known as N2K. For every unordered triple of three dice valued one
          through twenty, and every target number between one and nine hundred
          and ninety-nine, the almanac records the lowest-difficulty equation —
          if any — that uses each die exactly once.
        </p>
        <p>
          The dataset was generated by the project's TypeScript solver in a
          single sweep of the equation space. Difficulty is a heuristic score
          tuned by playtesting; smaller is easier. Negative scores mark trivial
          equations that any player would spot immediately.
        </p>
        <p>
          The almanac is published in {spellOut(editionCount)} editions,
          identical in content but wildly opposite in temperament — from a
          quiet parchment reference book to a green-on-black terminal
          reissue to a loud vermillion risograph zine, with a dozen further
          treatments in between. You are presently reading the{" "}
          <span style={{ color: "rgb(var(--accent-500))" }}>{activeTheme.label}</span> edition
          — <em>{activeTheme.tagline.toLowerCase()}</em>. Switch editions in
          the masthead at any time; your choice will be remembered.
        </p>
      </div>

      {index !== null && (
        <div className="mt-12 grid grid-cols-2 gap-x-10 gap-y-3 text-[13px] font-mono">
          <Field label="Compiled" value={new Date(index.generatedAt).toUTCString()} />
          <Field label="Dice range" value={`${index.diceMin}…${index.diceMax}`} />
          <Field label="Target range" value={`${index.totalMin}…${index.totalMax}`} />
          <Field label="Depower" value={index.depower ? "yes" : "no"} />
          <Field label="Triples" value={index.diceTriplesTotal.toLocaleString()} />
          <Field label="Records" value={index.recordsWritten.toLocaleString()} />
        </div>
      )}
    </article>
  );
});

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between border-b border-dotted border-ink-100/30 pb-1">
      <span className="uppercase tracking-wide-caps text-[10px] text-ink-100">{label}</span>
      <span className="text-ink-300 tabular">{value}</span>
    </div>
  );
}
